version: '3.9'

services:
  django:
    build:
      context: /server
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=djangobackend.settings  # Set your Django settings module
    volumes:
      - .:/app
    depends_on:
     - mongo
    restart: always

  nodeapp:
    image: nodeapp:lastest
    build:
      context: /functions
      dockerfile: Dockerfile.node
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://mongo:27017/mydatabase
    depends_on:
      - mongo
    restart: always

  flaskapp:
    build:
      context: /functions
      dockerfile: Dockerfile.flask
    ports:
      - "5000:5000"
    environment:
      - CLOUDANT_USERNAME=${CLOUDANT_USERNAME}
      - IAM_API_KEY=${IAM_API_KEY}
      - CLOUDANT_URL=${CLOUDANT_URL}
    depends_on:
     - mongo
    restart: always

  mongo:
    image: mongo:4.4
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always